version: "3.9"

services:
  redis:
    image: redis
    command: redis-server
    ports:
      - "6379:6379"
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
  web:
    build: .
    command: bash -c 'python manage.py migrate && python manage.py runserver 0.0.0.0:8000'
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db
  celery-worker:
    restart: always
    build:
      context: .
    command: celery -A coinmena worker -P eventlet -l info
    volumes:
      - ./app:/app
    env_file:
      - ./.env
    depends_on:
      - db
      - redis
  celery-beat:
    restart: always
    build:
      context: .
    command: celery -A coinmena beat -l info
    volumes:
      - ./app:/app
    env_file:
      - ./.env
    depends_on:
      - db
      - redis
  flower:
    restart: always
    build:
      context: .
    command: celery -A coinmena flower --broker=redis://redis:6379 --port=5555
    ports:
      - 5557:5555
    depends_on:
      - redis