# Generated by Django 3.2.9 on 2021-11-27 13:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ForexRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_curr_code', models.CharField(max_length=3)),
                ('from_curr_name', models.CharField(max_length=30)),
                ('to_curr_code', models.CharField(max_length=3)),
                ('to_curr_name', models.CharField(max_length=30)),
                ('exchange_rate', models.FloatField(default=0.0)),
                ('last_updated', models.DateTimeField()),
                ('time_zone', models.CharField(max_length=3)),
                ('bid_price', models.FloatField()),
                ('ask_price', models.FloatField()),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
